### ISSUE TITLE
Relevance to BigQuery Link?

### ISSUE THREAD

**Issue by stokedout** [aliasoblomov/Backfill-GA4-to-BigQuery#11]
Hey, I think this is misleading since most people will come here with the intention of fulfilling the lack of backfill feature when using  "BigQuery Link" in GA4.

Is there a way that you can make the extraction match the schema documented here?
https://support.google.com/analytics/answer/7029846?hl=en#zippy=%2Cevent%2Citems%2Cuser%2Cdevice%2Ctraffic-source%2Cstream-and-platform%2Cecommerce

**Comment by aliasoblomov** [comment]
Sadly, no, because the analytics public APIs do not support granular data such as user_pseudo_id and all events hits separately. Therefore, there's no way to fill the gaps with the same schema. However, the script does offer a variety of combinations of metrics and dimensions that can be useful to join with GA4 tables and provide a comprehensive analysis.
