### ISSUE TITLE
Table does not have a schema

### ISSUE THREAD

**Issue by r3volution11** [aliasoblomov/Backfill-GA4-to-BigQuery#5]
Hi Ali, I was going to message you on LinkedIn but that requires a Premium subscription so I thought I'd write an issue here instead.

As the title says, when I try running this script I get the following error:

`Error occurred: 400 Table [table_name]_c258d448_57dd_4d8d_b9bb_389ff6c3d6a3_source does not have a schema.; reason: invalid, message: Table [table_name]_c258d448_57dd_4d8d_b9bb_389ff6c3d6a3_source does not have a schema.`

I can see in the code that it should be generating the schema before uploading but for some reason that doesn't appear to be occurring.

I'm using the script as you provided it with only changes being made to the configuration variables.

I tried both creating a table in BigQuery first and also letting the script create a table from scratch. Both resulted in the same error.

Do I need to set the table up with a schema first? Am I missing something else?

**Comment by aliasoblomov** [comment]
Hi there, thank you for letting me know about the issue.

Don't worry, you might want to check your BigQuery as sometimes tables are created despite the error message. Another suggestion would be to switch to a different IDE, such as Google Colab. If the issue still persists, please send me your config.json file so that I can check if there are any issues there and help you resolve the problem.

**Comment by r3volution11** [comment]
It creates the table fine but it definitely doesn't create the schema and then populate it. 

I'm not sure how a different IDE can help. It's just 5 variables (6 technically, but one doesn't need to be changed).

My other guess is perhaps I grabbed the wrong Python dependencies. Based on the code I guessed what was needed until the script started working but there's a chance I grabbed one that "works" but isn't the correct one for your script. Could you detail the exact dependencies that are needed?

**Comment by aliasoblomov** [comment]
Colab can help you get rid of the hassle of checking the Python version and other dependencies. By the way, there is no specific dependency that causes any issue. This code has been running for more than 100 users in different environments correctly. If you're hands-on, you can add a schema field to ensure that it creates and populates fields correctly. Something like this:

```
schema = [
    bigquery.SchemaField("date", "DATE"),
    bigquery.SchemaField("sessionPrimaryChannelGroup", "STRING"),
    bigquery.SchemaField("sessions", "INTEGER"),
    bigquery.SchemaField("totalUsers", "INTEGER"),
    bigquery.SchemaField("newUsers", "INTEGER"),
    bigquery.SchemaField("ecommercePurchases", "INTEGER"),
    bigquery.SchemaField("purchaseRevenue", "FLOAT")
]
```

If not, email me your used code (metrics and dimensions) so that I can adjust it for you.
